"use client";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Github, Mail, Menu, X } from "lucide-react";
import { useState } from "react";
import { Project, projects } from "@/data/projects";

const filters = ["All", "SEO", "Web", "Social", "Email", "Video"] as const;
const rise = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.55 } };

export default function Portfolio() {
  const [filter, setFilter] = useState<(typeof filters)[number]>("All");
  const [active, setActive] = useState<Project | null>(null);
  const [menu, setMenu] = useState(false);
  const shown = filter === "All" ? projects : projects.filter((project) => project.category === filter);
  return <main>
    <nav className="nav"><a href="#top" className="brand">LAN ANH<span>®</span></a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></div><a className="nav-email" href="mailto:lananhvu.2502@gmail.com">Email <ArrowUpRight size={15}/></a><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button>{menu && <div className="mobile-menu"><a onClick={() => setMenu(false)} href="#work">Work</a><a onClick={() => setMenu(false)} href="#about">About</a><a onClick={() => setMenu(false)} href="#contact">Contact</a></div>}</nav>
    <section id="top" className="hero"><motion.p {...rise} className="eyebrow"><span className="status-dot"/> Available for remote opportunities · HCMC, Vietnam</motion.p><motion.h1 {...rise} transition={{ duration: .7, delay: .08 }}>Content with<br/><em>clarity</em> and <span>edge.</span></motion.h1><motion.div {...rise} transition={{ duration: .55, delay: .16 }} className="hero-bottom"><p>I&apos;m Vũ Thị Lan Anh — a C1-English content creator and AI-powered content marketer producing smart, human work for brands that want to move.</p><a href="#work" className="round-link">Explore work <ArrowUpRight size={18}/></a></motion.div><div className="stat-row">{[["C1", "English"], ["100%", "English content"], ["4", "Client brands"], ["6", "Content formats"]].map(([num, label]) => <div className="stat" key={label}><b>{num}</b><span>{label}</span></div>)}</div></section>
    <section id="work" className="work section"><motion.div {...rise} className="section-head"><p className="eyebrow">Selected work / 2024—2026</p><h2>Made to be<br/><em>noticed.</em></h2><p>Strategy, words, sites and stories — made for international B2B, local service and community brands.</p></motion.div><div className="filters" role="tablist">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "active" : ""}>{item}</button>)}</div><motion.div layout className="project-grid">{shown.map((project, i) => <motion.button layout key={project.id} className={`project-card ${i === 0 ? "featured" : ""}`} onClick={() => setActive(project)} whileHover={{ y: -7 }}><div className="image-wrap"><Image src={project.image} alt={project.title} fill sizes="(max-width: 700px) 100vw, 50vw"/><span className="image-arrow"><ArrowUpRight size={19}/></span></div><div className="project-meta"><span>{project.number} / {project.category}</span><span>{project.client}</span></div><h3>{project.title}</h3><p>{project.summary}</p></motion.button>)}</motion.div></section>
    <section id="about" className="about section"><div className="about-orb"/><motion.div {...rise} className="about-copy"><p className="eyebrow">How I work</p><h2>Human judgment.<br/>AI <em>velocity.</em></h2><p>I use ChatGPT, Claude and Codex from ideation to final edit — not as a replacement for taste, but to make the research, structure and iteration sharper.</p><div className="process"><span>01 / Find the signal</span><span>02 / Shape the story</span><span>03 / Make it move</span></div></motion.div><motion.div {...rise} className="about-note"><span>↗</span><p>From SEO articles and high-converting landing pages to social content, HTML emails and video: every deliverable is made in English, with a point of view.</p></motion.div></section>
    <section id="contact" className="contact section"><motion.div {...rise}><p className="eyebrow">Let&apos;s make something useful</p><h2>Have a project<br/>in <em>mind?</em></h2><p>For collaborations, content work or a full portfolio walkthrough, say hello.</p><div className="contact-actions"><a className="mail-link" href="mailto:lananhvu.2502@gmail.com">lananhvu.2502@gmail.com <ArrowUpRight/></a><a className="github-link" href="https://lananh-2502.github.io" target="_blank" rel="noreferrer"><Github size={18}/> GitHub</a></div></motion.div><ContactForm/></section>
    <footer><span>© 2026 Vũ Thị Lan Anh</span><span>Built for the internet, not a template.</span><a href="#top">Back to top ↑</a></footer>
    <AnimatePresence>{active && <CaseStudy project={active} onClose={() => setActive(null)}/>}</AnimatePresence>
  </main>;
}

function ContactForm() { const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle"); async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setState("sending"); const form = e.currentTarget; const data = new FormData(form); const fallback = () => { window.location.href = `mailto:lananhvu.2502@gmail.com?subject=${encodeURIComponent(String(data.get("subject") || "Portfolio enquiry"))}&body=${encodeURIComponent(`From: ${data.get("name")} (${data.get("email")})\n\n${data.get("message")}`)}`; setState("idle"); }; try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) }); if (response.ok) { setState("sent"); form.reset(); } else { fallback(); } } catch { fallback(); } }
return <form className="contact-form" onSubmit={submit}><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@company.com"/></label><label>Subject<input name="subject" placeholder="What are we making?"/></label><label>Message<textarea required name="message" rows={4} placeholder="Tell me a little about it."/></label><button disabled={state === "sending"} type="submit">{state === "sending" ? "Sending..." : state === "sent" ? "Sent — thank you!" : "Send a message"} <ArrowUpRight size={17}/></button>{state === "error" && <p className="form-error">Something went wrong. Please email directly instead.</p>}<a className="mailto-fallback" href="mailto:lananhvu.2502@gmail.com">Or send an email directly ↗</a></form>; }
function CaseStudy({ project, onClose }: { project: Project; onClose: () => void }) { return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.article className="case-study" initial={{ y: 40 }} animate={{ y: 0 }} exit={{ y: 40 }} onClick={(e) => e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><div className="case-image"><Image src={project.image} alt="" fill sizes="90vw"/></div><p className="eyebrow">{project.number} / {project.category} / {project.client}</p><h2>{project.title}</h2><p className="case-summary">{project.summary}</p><div className="case-columns"><div><span>Challenge</span><p>{project.challenge}</p></div><div><span>Approach</span>{project.approach.map(x => <p key={x}>— {x}</p>)}</div></div><div className="outcomes">{project.outcomes.map(x => <b key={x}>{x}</b>)}</div>{project.href && <a className="visit" href={project.href} target="_blank" rel="noreferrer">View live work <ArrowUpRight/></a>}</motion.article></motion.div> }
